# Generated by Django 5.0.4 on 2024-04-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recorder',
            new_name='Record',
        ),
    ]
